include: package:very_good_analysis/analysis_options.yaml
analyzer:
  strong-mode:
     implicit-casts: true
     implicit-dynamic: true
  errors:
    missing_required_param: error
    prefer_const_declarations: warning
    prefer_const_constructors: warning
    import_of_legacy_library_into_null_safe: warning
    public_member_api_docs: ignore
    
linter:
  rules:
    omit_local_variable_types: false
    # missing_required_param: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    public_member_api_docs: false
    use_key_in_widget_constructors: true
    prefer_int_literals: true
    lines_longer_than_80_chars: false
    prefer_relative_imports: true
    always_use_package_imports: false
    # import_of_legacy_library_into_null_safe: true
    avoid_print: true
    prefer_single_quotes: true
    avoid_redundant_argument_values: true
    unnecessary_parenthesis: true
    prefer_final_locals: true
    avoid_dynamic_calls: false
    sort_constructors_first: false
    sort_pub_dependencies: false
    avoid_positional_boolean_parameters: false
    use_build_context_synchronously: false
    use_setters_to_change_properties: false
    avoid_bool_literals_in_conditional_expressions: false